import fs from 'fs';

const referenceGroups = [
  { code: 'country', name: 'Country' },
  { code: 'province', name: 'Province' },
  { code: 'city', name: 'City' },
  { code: 'timezone', name: 'Timezone' },
  { code: 'currency', name: 'Currency' },
  { code: 'language', name: 'Language' },
  { code: 'gender', name: 'Gender' },
  { code: 'religion', name: 'Religion' },
  { code: 'blood_type', name: 'Blood Type' },
  { code: 'nationality', name: 'Nationality' },
  { code: 'marital_status', name: 'Marital Status' },
  { code: 'employment_type', name: 'Employment Type' },
  { code: 'employment_status', name: 'Employment Status' },
  { code: 'department_type', name: 'Department Type' },
  { code: 'position_level', name: 'Position Level' },
  { code: 'job_grade', name: 'Job Grade' },
  { code: 'customer_category', name: 'Customer Category' },
  { code: 'customer_industry', name: 'Customer Industry' },
  { code: 'customer_type', name: 'Customer Type' },
  { code: 'vendor_category', name: 'Vendor Category' },
  { code: 'vendor_type', name: 'Vendor Type' },
  { code: 'warehouse_type', name: 'Warehouse Type' },
  { code: 'warehouse_status', name: 'Warehouse Status' },
  { code: 'inventory_category', name: 'Inventory Category' },
  { code: 'inventory_unit', name: 'Inventory Unit' },
  { code: 'inventory_brand', name: 'Inventory Brand' },
  { code: 'inventory_condition', name: 'Inventory Condition' },
  { code: 'asset_category', name: 'Asset Category' },
  { code: 'asset_type', name: 'Asset Type' },
  { code: 'asset_status', name: 'Asset Status' },
  { code: 'asset_ownership', name: 'Asset Ownership' },
  { code: 'project_status', name: 'Project Status' },
  { code: 'project_priority', name: 'Project Priority' },
  { code: 'project_type', name: 'Project Type' },
  { code: 'task_status', name: 'Task Status' },
  { code: 'task_priority', name: 'Task Priority' },
  { code: 'ticket_category', name: 'Ticket Category' },
  { code: 'ticket_priority', name: 'Ticket Priority' },
  { code: 'ticket_impact', name: 'Ticket Impact' },
  { code: 'ticket_urgency', name: 'Ticket Urgency' },
  { code: 'ticket_status', name: 'Ticket Status' },
  { code: 'ticket_source', name: 'Ticket Source' },
  { code: 'resolution_code', name: 'Resolution Code' },
  { code: 'sla_level', name: 'SLA Level' },
  { code: 'invoice_status', name: 'Invoice Status' },
  { code: 'payment_status', name: 'Payment Status' },
  { code: 'payment_method', name: 'Payment Method' },
  { code: 'expense_category', name: 'Expense Category' },
  { code: 'tax_type', name: 'Tax Type' },
  { code: 'attendance_status', name: 'Attendance Status' },
  { code: 'leave_type', name: 'Leave Type' },
  { code: 'shift_type', name: 'Shift Type' },
  { code: 'training_category', name: 'Training Category' },
  { code: 'performance_category', name: 'Performance Category' }
];

console.log('Groups size:', referenceGroups.length);

